name: Build CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  gqltools:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Get Go dependencies
        run: go get -v -t -d ./...

      - name: test
        run: go test -v -race ./...

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --timeout=3m12s
          skip-go-installation: true
          skip-pkg-cache: true
          skip-build-cache: true

      - name: "Check: go fmt"
        run: |
          if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
              gofmt -s -l -d .
              echo "Please run: go fmt ./..."
              exit 1
          fi
          if [ "$(go mod tidy -v | wc -l)" -gt 0 ]; then
              go mod tidy -v
              echo "Please run: go mod tidy"
              exit 1
          fi

      - name: Build
        run: |
          make build